# Tensorflow Developer Certificate Preparation
___
## Introduction to Tensorflow in Python - DataCamp - ML-Scientist-Career-Track - by Isaiah Hull
___
## Chapter 1.2- Basic Operations

### 1. Basic operations
In this notebook, we'll talk about basic operations in TensorFlow.

### 2. What is a TensorFlow operation?
- TensorFlow has a model of computation that revolves around the use of graphs. 
- A TensorFlow graph contains edges and nodes, where the edges are tensors and the nodes are operations.
- In the graph shown, which was drawn using TensorFlow, the const operations define 2 by 2 constant tensors. 
- Two tensors are summed using the add operation.
- Another two tensors are then summed using the add operation.
- Finally, the resulting matrices are multiplied together with the matmul operation.
![Figure](https://github.com/salmankhaliq22/TF-Developer-Certificate/blob/main/01-Intro-to-tensorflow-in-python-DC/1.2.1.PNG)
<img src="https://github.com/salmankhaliq22/TF-Developer-Certificate/blob/main/01-Intro-to-tensorflow-in-python-DC/1.2.1.PNG" />
<img title="a title" alt="Alt text" src="/images/boo.svg">
![](https://github.com/salmankhaliq22/TF-Developer-Certificate/blob/main/01-Intro-to-tensorflow-in-python-DC/1.2.1.PNG)

### 3. Applying the addition operator
Let's start with the addition operator. 
- We will first import the constant and add operations. 
- We may now use constant to define 0-dimensional, 1-dimensional, and 2-dimensional tensors.

In [1]:
# Import constant and add from tensorflow
from tensorflow import constant, add

# Define 0-dimensional tensors
A0 = constant([1])
B0 = constant([2])

# Define 1-dimensional tensors
A1 = constant([1,2])
B1 = constant([3,4])

# Define 2-dimensional tensors
A2 = constant([[1,2], [3,4]])
B2 = constant([[5,6], [7,8]])

# Printing
print(A0)
print(B0)
print(A1)
print(B1)
print(A2)
print(B2)

tf.Tensor([1], shape=(1,), dtype=int32)
tf.Tensor([2], shape=(1,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


- Finally, let's add them together using the operation for tensor addition. 
- Note that we can perform scalar addition with A0 and B0, vector addition with A1 and B1, and matrix addition with A2 and B2.

In [2]:
# Perform tensor addition with  add()
C0 = add(A0, B0)
C1 = add(A1, B1)
C2 = add(A2, B2)

print(C0)
print(C1)
print(C2)

tf.Tensor([3], shape=(1,), dtype=int32)
tf.Tensor([4 6], shape=(2,), dtype=int32)
tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


### 4. Performing tensor addition
- The ``add()`` operation performs **element-wise addition** with two tensors. 
- Each pair of tensors added must have the same shape. 
    - Element-wise addition of the scalars 1 and 2 yields the scalar 3. 
    - Element-wise addition of the vectors 1,2 and 3,4 yields the vector 4,6. 
    - Element-wise addition of the matrices 1,2,3,4 and 5,6,7,8 yields the matrix 6,8,10,12. 
![1.2.2](1.2.2.png "Figure 1.2.2")
- Furthermore, the ``add()`` operator is overloaded, which means that we can also perform addition using the ``+`` symbol.

___
### 5. How to perform multiplication in TensorFlow
We will consider both **element-wise** and **matrix multiplication**.   
- For **element-wise multiplication**, which is performed with the ``multiply()`` operation, 
    - The tensors involved must have the same shape. 
    - For instance, you may want to multiply the vector 1,2,3 by 3,4,5 or 1,2 by 3,4. 
- For **matrix multiplication**, you use the ``matmul()`` operator. 
    - The ``matmul(A,B)`` operation multiplies A by B.
    - Note that performing ``matmul(A,B)`` requires that the **number of columns of A** ``=`` **the number of rows of B**.

### 6. Applying the multiplication operators
Let's look at some examples of multiplication in TensorFlow. 
- We'll import the ``ones()`` operator, along with the two types of multiplication we will use. 
- We will also define a ``scalar``, ``A0``, a ``3 by 1`` vector of ones, a ``3 by 4`` vector of ones, and a ``4 by 3`` vector of ones. 

In [3]:
# importing operators from tensorflow
from tensorflow import  ones, matmul, multiply

# Define tensors
A0 = ones(1)
A1 = ones([3,1])
A2 = ones([3,4])
A3 = ones([4,3])

print(A0)
print(A1)
print(A2)
print(A3)

tf.Tensor([1.], shape=(1,), dtype=float32)
tf.Tensor(
[[1.]
 [1.]
 [1.]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


- What operations can be performed using these tensors of ones? 
    - We can perform **element-wise multiplication** of any element by itself, 
        - such as ``multiply(A0, A0)``, ``multiply(A31, A31)``, or ``multiply(A34, A34)``. 
    - We can also perform **matrix multiplication** 
        - such as ``matmul(A43, A34)``, **but not** ``matmul(A43, A43)``.
___

### 7. Summing over tensor dimensions
Finally, we end this lesson by discussing summation over tensors, which is performed using the ``reduce_sum()`` operator.
- ``reduce_sum(A)`` can be used to **sum over all dimensions of a tensor** or **just one** ``reduce_sum(A,i)``. 

Let's see how this works in practice. 
- We will import ``ones`` and ``reduce_sum`` from tensorflow. 
- We will then define a ``2x3x4`` tensor that consists of ones.

In [4]:
# import operations from tensorflow
from tensorflow import ones, reduce_sum

# Define a 2x3x4 tensor of ones
A = ones([2,3,4])

print(A)

tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)


- If we **sum over all elements of A**, we get **24**, since the tensor contains 24 elements, all of which are 1. 
- If we **sum over dimension 0**, we get a **3x4 matrix of 2s**. 
- If we **sum over 1**, we get a **2x4 matrix of 3s**. 
- And if we **sum over 2**, we get a **2x3 matrix of 4s**. 
- In each case, we reduce the size of the tensor by summing over one of its dimensions.

In [5]:
# sum over all dimensions
B = reduce_sum(A)

# sum over dimensions 0, 1, 2
B0 = reduce_sum(A,0)
B1 = reduce_sum(A,1)
B2 = reduce_sum(A,2)

# printing
print(B0)
print(B1)
print(B2)

tf.Tensor(
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]], shape=(3, 4), dtype=float32)
tf.Tensor(
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[4. 4. 4.]
 [4. 4. 4.]], shape=(2, 3), dtype=float32)
